# Generated by Django 6.1 on 2026-08-12 14:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tournament_type', models.CharField(choices=[('GROUP_STAGE', 'Group Stage'), ('KNOCKOUT', 'Knockout'), ('GROUP_AND_KNOCKOUT', 'Group and Knockout')], default='GROUP_AND_KNOCKOUT', max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REGISTRATION', 'Registration'), ('DRAWING', 'Drawing'), ('GROUP_STAGE', 'Group Stage'), ('KNOCKOUT', 'Knockout'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=32)),
                ('max_players', models.PositiveIntegerField(default=32)),
                ('number_of_groups', models.PositiveIntegerField(default=8)),
                ('players_per_group', models.PositiveIntegerField(default=4)),
                ('qualification_count', models.PositiveIntegerField(default=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('rules', models.TextField(blank=True)),
                ('draw_mode', models.CharField(choices=[('RANDOM', 'Random'), ('SEEDED', 'Seeded'), ('BALANCED', 'Balanced')], default='RANDOM', max_length=20)),
                ('randomization_seed', models.CharField(blank=True, max_length=255, null=True)),
                ('draw_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('group_number', models.PositiveIntegerField()),
                ('max_players', models.PositiveIntegerField(default=4)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['group_number'],
                'unique_together': {('tournament', 'group_number'), ('tournament', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.PositiveIntegerField(blank=True, null=True)),
                ('registration_status', models.CharField(choices=[('REGISTERED', 'Registered'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='REGISTERED', max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='tournaments.tournamentgroup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['tournament', 'seed', 'joined_at'],
                'unique_together': {('tournament', 'player')},
            },
        ),
    ]
